import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
const root=path.resolve('../..')
const workspace=JSON.parse(fs.readFileSync(path.join(root,'.local/browser-workspace.json'),'utf8')) as { workspace_id:string; email:string; password:string }
const catalog='SKU,Product name,Manufacturer,Model,MPN,Size,Coating,Material,Length,Pairs per pack,Cut rating,Touchscreen,Certification,Legacy note\nBROWSER-001,ForgeWorks FG-100 · M,ForgeWorks,FG-100,FG-100-M-N,M,Nitrile,,,,,,,Preserve this original column\n'
const schema=JSON.parse(fs.readFileSync(path.join(root,'fixtures/category.json'),'utf8'))

test('import → ingest → conflict review → approve → export, with source navigation',async ({page})=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill(workspace.email)
 await page.getByLabel('Password',{exact:true}).fill(workspace.password)
 await page.getByRole('button',{name:'Sign in to workspace'}).click()
  await expect(page.getByRole('heading',{name:'A clearer picture of your products.'})).toBeVisible()
  await page.getByLabel('Workspace',{exact:true}).selectOption(workspace.workspace_id)
  // Category creation uses the same authenticated API; subsequent schema editing is exercised in the UI.
  await page.evaluate(async ({definition,wid})=>{
    const me=await fetch('/api/auth/me').then(r=>r.json())
    const response=await fetch('/api/categories',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':me.csrf,'x-workspace-id':wid},body:JSON.stringify(definition)})
    if(!response.ok) throw new Error(await response.text())
  },{definition:schema,wid:workspace.workspace_id})
  await page.getByRole('link',{name:'Import catalog',exact:true}).first().click()
  await page.getByLabel('Upload catalog CSV').setInputFiles({name:'browser-catalog.csv',mimeType:'text/csv',buffer:Buffer.from(catalog)})
  await expect(page.getByRole('heading',{name:'Match your columns'})).toBeVisible()
  await expect(page.getByLabel('Map sku',{exact:true})).toHaveValue('SKU')
  await page.getByRole('button',{name:'Import 1 products'}).click()
  await expect(page.getByText('BROWSER-001',{exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Source library',exact:true}).click()
  await page.getByLabel('Add source documents').setInputFiles([path.join(root,'fixtures/sources/01-technical-records.txt'),path.join(root,'fixtures/sources/04-conflicting-record.txt')])
  await expect(page.locator('tbody .status-ready')).toHaveCount(2)
  await page.getByRole('link',{name:'Product catalog',exact:true}).click()
  await page.getByLabel('Select BROWSER-001',{exact:true}).check()
  await page.getByRole('button',{name:/Enrich selected/}).click()
  await page.getByRole('button',{name:'Start enrichment',exact:true}).click()
  await expect(page.getByRole('link',{name:'Review',exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Review',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Current record'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Supporting evidence'})).toBeVisible()
  await expect(page.locator('.status-conflicting')).toHaveCount(2)
  const nylon=page.locator('.proposal-card').filter({hasText:'Liner material'}).filter({hasText:'Nylon'})
  await nylon.locator('.evidence-link').click()
  await expect(page.locator('.evidence-panel blockquote')).toContainText('Material: Nylon')
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:path.join(root,'docs/screenshots/review-conflict.png'),fullPage:true})
  await page.getByRole('link',{name:'Open extracted passage'}).first().click()
  await expect(page.locator('.passage-card.highlighted')).toBeVisible()
  await page.goBack()
  await expect(page.locator('.status-conflicting')).toHaveCount(2)
  await page.locator('.proposal-card').filter({hasText:'Liner material'}).filter({hasText:'Nylon'}).getByRole('button',{name:'Approve Liner material'}).click()
  await page.getByLabel('Decision reason').fill('Primary technical record chosen after comparing both documents.')
  await page.getByRole('button',{name:'Approve selected value',exact:true}).click()
  await expect(page.locator('.status-conflicting')).toHaveCount(0)
  await page.getByText('Select supported',{exact:true}).click()
  await page.getByRole('button',{name:/^Approve 4$/}).click()
  await expect(page.locator('.status-approved')).toHaveCount(5)
  const missing=page.locator('.proposal-card').filter({hasText:'Certification'})
  await missing.getByRole('button',{name:'Reject Certification'}).click()
  await expect(page.getByText('Review complete. Approved values are now part of the catalog.')).toBeVisible()
  await page.getByRole('link',{name:'Exports',exact:true}).click()
  await page.getByRole('button',{name:'Create export',exact:true}).click()
  const downloadEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download',exact:true}).first().click()
  const download=await downloadEvent
  await download.saveAs(path.join(root,'.local/browser-verified-export.zip'))
  expect(fs.statSync(path.join(root,'.local/browser-verified-export.zip')).size).toBeGreaterThan(500)
  await page.getByRole('link',{name:'Category schemas',exact:true}).click()
  await page.getByRole('button',{name:'Add attribute',exact:true}).click()
  const attribute=page.locator('.attribute-editor').last()
  await attribute.getByLabel('Key',{exact:true}).fill('review_note')
  await attribute.getByLabel('Display name',{exact:true}).fill('Review note')
  await page.getByRole('button',{name:'Save new version',exact:true}).click()
  await expect(page.getByText(/Saved as version 2/)).toBeVisible()
  await page.getByRole('link',{name:'Settings',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Settings & provider status'})).toBeVisible()
  await page.getByRole('link',{name:'Overview',exact:true}).click()
  await expect(page.getByRole('heading',{name:'A clearer picture of your products.'})).toBeVisible()
  await page.screenshot({path:path.join(root,'docs/screenshots/overview.png'),fullPage:true})
  expect(errors).toEqual([])
})

test('tablet layout keeps catalog navigation and controls available',async({page})=>{
  await page.setViewportSize({width:820,height:1180})
  await page.goto('/')
  await page.getByLabel('Email',{exact:true}).fill(workspace.email)
 await page.getByLabel('Password',{exact:true}).fill(workspace.password)
 await page.getByRole('button',{name:'Sign in to workspace'}).click()
  await expect(page.getByRole('heading',{name:'A clearer picture of your products.'})).toBeVisible()
  await page.goto('/catalog')
  await expect(page.getByRole('heading',{name:'Product catalog',exact:true})).toBeVisible()
  await expect(page.getByLabel('Search products')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:path.join(root,'docs/screenshots/tablet.png'),fullPage:true})
})


test('guided examples explain outcomes, filter proposals and keep unknown fields empty',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Email',{exact:true}).fill(workspace.email)
 await page.getByLabel('Password',{exact:true}).fill(workspace.password)
 await page.getByRole('button',{name:'Sign in to workspace'}).click()
 await expect(page.getByRole('heading',{name:'A clearer picture of your products.'})).toBeVisible()
 await page.getByRole('link',{name:'Guided examples',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Everyday examples',exact:true})).toBeVisible()
 await expect(page.locator('.example-card')).toHaveCount(12)
 const setup=page.getByRole('button',{name:/Set up guided examples|Open example workspace/})
 if(await setup.isVisible()) await setup.click()
 await expect(page.getByText('Example workspace is open',{exact:true})).toBeVisible()
 await expect(page.getByText('5 / 5 sources ready',{exact:true})).toBeVisible()
 await page.screenshot({path:path.join(root,'docs/screenshots/guided-examples.png'),fullPage:true})
 const example=page.locator('.example-card').filter({hasText:'NS-005'})
 await example.getByRole('button',{name:/Try this example|Open review/}).click()
 await expect(page.getByRole('heading',{name:'Current record'})).toBeVisible()
 await expect(page.locator('.status-insufficient_evidence')).toHaveCount(1)
 await page.getByLabel('Proposal filter',{exact:true}).selectOption('insufficient_evidence')
 await expect(page.locator('.proposal-card')).toHaveCount(1)
 await page.getByRole('button',{name:'Keep 1 unknown',exact:true}).click()
 await page.getByRole('button',{name:'Confirm unknown fields',exact:true}).click()
 await expect(page.getByText('Review complete. No values were added to the catalog.')).toBeVisible()
 const values=page.locator('.current-values').getByText('Pairs per pack',{exact:true}).locator('..')
 await expect(values).toContainText('Unknown')
})

test('session expiry during navigation returns to login and preserves the catalog',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Email',{exact:true}).fill(workspace.email)
 await page.getByLabel('Password',{exact:true}).fill(workspace.password)
 await page.getByRole('button',{name:'Sign in to workspace'}).click()
 await expect(page.getByRole('heading',{name:'A clearer picture of your products.'})).toBeVisible()
 await page.context().clearCookies()
 await page.getByRole('link',{name:'Product catalog',exact:true}).click()
 await expect(page.getByRole('button',{name:'Sign in to workspace'})).toBeVisible()
 await expect(page.getByText('Your session expired. Sign in again to continue. Saved work is preserved.')).toBeVisible()
 await page.getByLabel('Email',{exact:true}).fill(workspace.email)
 await page.getByLabel('Password',{exact:true}).fill(workspace.password)
 await page.getByRole('button',{name:'Sign in to workspace'}).click()
 await expect(page.getByRole('heading',{name:'Product catalog',exact:true})).toBeVisible()
 await expect(page.getByText('BROWSER-001',{exact:true})).toBeVisible()
})


test('public product presentation works without a session and adapts to mobile', async ({page}) => {
  await page.goto('/product-story')
  await expect(page.getByRole('heading', {name: 'Better product data. A reason for every change.'})).toBeVisible()
  await expect(page.getByText('Fixture attribute checks', {exact:true})).toBeVisible()
  const summary = await page.request.get('/verification-summary.json')
  expect(summary.ok()).toBeTruthy()
  expect((await summary.json()).remote_ci_executed).toBe(false)
  for (const image of await page.locator('.story-capture-grid img').all()) {
    await image.scrollIntoViewIfNeeded()
    await expect.poll(()=>image.evaluate((element:HTMLImageElement)=>element.complete && element.naturalWidth > 0)).toBeTruthy()
  }
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:path.join(root,'docs/screenshots/product-story.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:path.join(root,'docs/screenshots/product-story-mobile.png'),fullPage:true})
  await page.getByRole('link',{name:'Try the walkthrough',exact:true}).click()
  await expect(page.getByRole('button',{name:'Sign in to workspace'})).toBeVisible()
  await page.getByLabel('Email',{exact:true}).fill(workspace.email)
  await page.getByLabel('Password',{exact:true}).fill(workspace.password)
  await page.getByRole('button',{name:'Sign in to workspace'}).click()
  await expect(page.getByRole('heading',{name:'One product. A defensible decision.'})).toBeVisible()
})

test('guided walkthrough opens the actual PDF, shows checkpoints and preserves the reviewed result', async ({page}) => {
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/walkthrough')
  await page.getByLabel('Email',{exact:true}).fill(workspace.email)
  await page.getByLabel('Password',{exact:true}).fill(workspace.password)
  await page.getByRole('button',{name:'Sign in to workspace'}).click()
  await page.getByRole('button',{name:/Start guided walkthrough|Resume walkthrough/}).click()
  await expect(page.getByText('Your walkthrough is open',{exact:true})).toBeVisible()
  await expect(page.locator('.walkthrough-sources .status-ready')).toHaveCount(2)
  await page.getByRole('button',{name:'Prepare proposals',exact:true}).click()
  await expect(page.getByRole('link',{name:'Compare evidence',exact:true})).toBeVisible()
  await page.screenshot({path:path.join(root,'docs/screenshots/walkthrough.png'),fullPage:true})
  await page.getByRole('link',{name:'Compare evidence',exact:true}).click()
  await expect(page.locator('.status-conflicting')).toHaveCount(4)
  const material=page.locator('.proposal-card').filter({hasText:'Liner material'}).filter({hasText:'Nylon'})
  await material.locator('.evidence-link').click()
  await page.getByRole('button',{name:'Inspect original source',exact:true}).first().click()
  const dialog=page.getByRole('dialog')
  await expect(dialog.getByText('Quoted passage highlighted on this page.',{exact:true})).toBeVisible()
  await expect(dialog.locator('.citation-highlight')).toContainText('Material: Nylon')
  await page.keyboard.press('Alt+ArrowDown')
  await expect(dialog.locator('.citation-value')).toHaveText('Nylon')
  await dialog.screenshot({path:path.join(root,'docs/screenshots/pdf-evidence.png')})
  await dialog.getByLabel('PDF zoom',{exact:true}).selectOption('1.25')
  await expect(dialog.locator('.citation-highlight')).toContainText('Material: Nylon')
  await dialog.getByLabel('PDF page',{exact:true}).fill('3')
  await dialog.getByLabel('PDF page',{exact:true}).press('Tab')
  await expect(dialog.getByText(/The exact quotation could not be located/)).toBeVisible()
  await page.keyboard.press('Escape')
  await material.getByRole('button',{name:'Approve Liner material'}).click()
  await page.getByLabel('Decision reason').fill('The exact manufacturer datasheet identifies Nylon for this part.')
  await page.getByRole('button',{name:'Approve selected value',exact:true}).click()
  await expect(material.locator('.status-approved')).toBeVisible()
  const pack=page.locator('.proposal-card').filter({hasText:'Pairs per pack'}).filter({hasText:'12'})
  await pack.getByRole('button',{name:'Approve Pairs per pack'}).click()
  await page.getByLabel('Decision reason').fill('The technical sheet explicitly specifies 12 pairs per box.')
  await page.getByRole('button',{name:'Approve selected value',exact:true}).click()
  await expect(pack.locator('.status-approved')).toBeVisible()
  await page.getByText('Select supported',{exact:true}).click()
  await page.getByRole('button',{name:/^Approve 1$/}).click()
  await expect(page.getByText('Review complete. Approved values are now part of the catalog.')).toBeVisible()
  await expect(page.locator('.event-log').getByText('Workflow completed',{exact:true})).toBeVisible()
  await expect(page.locator('.decision-ledger')).toContainText('The technical sheet explicitly specifies 12 pairs per box.')
  await page.getByLabel('Saved checkpoint',{exact:true}).selectOption({index:2})
  await expect(page.locator('.checkpoint-details')).toContainText('Next nodes')
  await page.getByRole('region',{name:'Execution timeline'}).screenshot({path:path.join(root,'docs/screenshots/execution-timeline.png')})
  await page.getByRole('link',{name:'See before & after',exact:true}).click()
  await expect(page.locator('.walkthrough-record')).toContainText('Nylon')
  await expect(page.locator('.walkthrough-record')).toContainText('250')
  await page.reload()
  await expect(page.getByRole('heading',{name:'Your decision, reflected in the catalog'})).toBeVisible()
  expect(errors).toEqual([])
})
