<script setup lang="ts">
import { ArrowRight, Database, FileSearch, GitBranch, ShieldCheck, Users } from '@lucide/vue'
import facts from '@/content/verification.json'
import BrandMark from '@/components/BrandMark.vue'
const principles = [
  { number:'01', title:'Match the product first', text:'Manufacturer, model, part number and variant constrain retrieval. A similar product is not evidence for this one.' },
  { number:'02', title:'Keep the original', text:'Imported values remain available. Proposed changes and approved values are stored separately, with a revision history.' },
  { number:'03', title:'Make uncertainty visible', text:'Conflicting sources require a choice. Missing information stays unknown. Manual edits are labeled explicitly.' },
  { number:'04', title:'Resume without duplicating', text:'A durable queue, transaction boundaries, idempotent reviews and PostgreSQL checkpoints preserve work across interruptions.' },
]
</script>
<template>
  <div class="product-story">
    <header class="story-nav"><RouterLink to="/product-story" class="brand"><BrandMark />CatalogForge</RouterLink><nav aria-label="Product navigation"><a href="#how-it-works">How it works</a><a href="#engineering">Engineering</a><a href="#verification">Verification</a></nav><RouterLink to="/walkthrough" class="button-primary">Try the walkthrough <ArrowRight :size="15"/></RouterLink></header>
    <main class="story-main">
      <section class="story-hero"><div><span class="story-chip">EVIDENCE-BACKED CATALOG ENRICHMENT</span><h1>Better product data.<br/><em>A reason for every change.</em></h1><p>CatalogForge helps catalog teams turn scattered product documents into structured proposals, compare conflicting sources and approve only the changes they can defend.</p><div class="story-hero-actions"><RouterLink to="/walkthrough" class="button-primary">Explore a real workflow <ArrowRight :size="17"/></RouterLink><a href="#how-it-works" class="button-outline">See how it works</a></div><span class="story-caption">Interactive walkthrough with fictional products. No model API key required in fixture mode.</span></div><div class="story-evidence-scene"><div class="scene-source"><FileSearch :size="22"/><span>TECHNICAL DATASHEET</span><strong>PrecisionGrip PG-210</strong><p>Material: <mark>Nylon</mark><br/>Length: <mark>25 cm</mark><br/>Qty per box: <mark>12 pairs</mark></p><small>Illustrative view · synthetic source</small></div><div class="scene-decision"><span class="status status-conflicting">Sources disagree</span><h3>Liner material</h3><div><strong>Nylon</strong><span>Technical sheet</span></div><div><strong>Polyester</strong><span>Supplier listing</span></div><p><Users :size="16"/>A reviewer makes the choice.</p></div></div></section>
      <div class="story-value-strip"><span><FileSearch :size="19"/>Sources beside proposals</span><span><ShieldCheck :size="19"/>Explicit human approval</span><span><GitBranch :size="19"/>Resumable workflows</span></div>
      <section id="how-it-works" class="story-section"><span class="eyebrow">THE WORKFLOW</span><h2>From scattered documents<br/>to a reviewable catalog.</h2><p class="story-lead">Built for the moment when a product record is incomplete and its sources do not quite agree.</p><div class="story-flow"><article><span>01</span><h3>Import</h3><p>Map CSV columns and preserve the original records.</p></article><article><span>02</span><h3>Find evidence</h3><p>Ingest PDFs, CSV and text. Retrieve passages for the exact product.</p></article><article><span>03</span><h3>Review</h3><p>Inspect citations, compare alternatives and explain a decision.</p></article><article><span>04</span><h3>Export</h3><p>Deliver original and approved values with an evidence report.</p></article></div></section>
      <section class="story-captures"><span class="eyebrow">INSIDE THE APPLICATION</span><h2>Inspect the source. Follow the decision.</h2><p class="story-lead">Actual local captures using fictional Northstar records. Open an image to inspect it at full size.</p><div class="story-capture-grid"><figure><a href="/images/evidence-inspector.png" target="_blank" rel="noopener"><img src="/images/evidence-inspector.png" alt="The original Northstar PDF beside a Nylon proposal, with Material: Nylon highlighted on page one" width="1420" height="940" loading="lazy"/></a><figcaption><strong>The original beside the quotation</strong><span>Page navigation, literal text highlighting and preserved source identity.</span></figcaption></figure><figure><a href="/images/execution-history.png" target="_blank" rel="noopener"><img src="/images/execution-history.png" alt="Execution timeline with recorded workflow events, saved checkpoints and reviewer decisions" loading="lazy"/></a><figcaption><strong>A readable execution history</strong><span>Persisted events, checkpoint inspection and explicit reviewer reasons.</span></figcaption></figure></div></section>
      <section id="engineering" class="story-section engineering-section"><div><span class="eyebrow">ENGINEERING DECISIONS</span><h2>Trust is part of the workflow.</h2><p class="story-lead">The design separates extraction, validation and approval so that each has a clear responsibility.</p></div><div class="principles-grid"><article v-for="principle in principles" :key="principle.number"><span>{{ principle.number }}</span><h3>{{ principle.title }}</h3><p>{{ principle.text }}</p></article></div><div class="architecture-map" aria-label="System architecture"><div><strong>Vue workspace</strong><span>Review · evidence viewer · execution history</span></div><ArrowRight/><div><strong>FastAPI</strong><span>Authentication · transactions · permissions</span></div><ArrowRight/><div><strong>Durable worker</strong><span>LangGraph · LangChain · Procrastinate</span></div><div class="architecture-storage"><Database :size="18"/><strong>PostgreSQL + pgvector</strong><span>Catalog revisions · retrieval · queue · checkpoints</span></div></div></section>
      <section id="verification" class="story-section"><span class="eyebrow">MEASURED, WITH SCOPE</span><h2>Verification you can inspect.</h2><p class="story-lead">Local execution recorded on {{ facts.date }}. Deterministic integration results are separate from live-model quality.</p><div class="story-proof-grid"><article><strong>{{ facts.backend + facts.frontend + facts.browser }}</strong><h3>Automated checks passed</h3><p>{{ facts.backend }} backend · {{ facts.frontend }} unit · {{ facts.browser }} browser acceptance</p></article><article><strong>319 / 319</strong><h3>Fixture attribute checks</h3><p>50 baseline products and 12 guided examples. Synthetic inputs with labeled expected outcomes.</p></article><article><strong>1×</strong><h3>Approval applied after recovery</h3><p>A worker was killed during an approval. Recovery preserved the candidate and applied one product revision.</p></article></div><p class="story-lead">Separate live evaluation: {{ facts.live_holdout.correct_proposals }}/{{ facts.live_holdout.proposals }} proposals matched the versioned labels, covering {{ facts.live_holdout.covered_fields }}/{{ facts.live_holdout.answerable_fields }} answerable fields across {{ facts.live_holdout.products }} held-out products. One incorrect proposal and two adversarial unit-conversion omissions remain. Labels have no independent expert review; every proposal still requires a reviewer.</p><div class="story-limitations"><ShieldCheck :size="22"/><div><h3>What these results establish</h3><p>Integration, review consistency and the observed recovery scenario. The live sample covers one manufacturer and category. Production load and remote CI were not evaluated. PDFs require an extractable text layer; scanned documents are not supported.</p><a href="/verification-summary.json" class="text-link" download>Download the verification summary <ArrowRight :size="14"/></a></div></div></section>
      <section class="story-final"><span class="eyebrow">SEE THE DECISION FOR YOURSELF</span><h2>Open the source.<br/>Compare the evidence.<br/>Make the call.</h2><RouterLink to="/walkthrough" class="button-primary">Start guided walkthrough <ArrowRight :size="18"/></RouterLink><p>One fictional product, two sources and a complete review.</p></section>
    </main><footer class="story-footer-bar"><span class="brand"><BrandMark />CatalogForge</span><span>Original records preserved. Every change reviewed.</span><RouterLink to="/">Open workspace <ArrowRight :size="14"/></RouterLink></footer>
  </div>
</template>
