<script setup lang="ts">
import { ShieldCheck, Sparkles, SlidersHorizontal, Server } from '@lucide/vue'
import { useData } from '@/composables/data'
import Notice from '@/components/Notice.vue'
import OperationsPanel from '@/components/OperationsPanel.vue'
type Config = { ai_limits: { provider_retries:number; input_tokens:number; output_tokens:number; scope_calls:number; workspace_calls:number }; mode:string; chat_model:string; embedding_space:string; credentials_configured:boolean; provider_ready:boolean; max_retrieval_rounds:number; max_run_seconds:number; worker_concurrency:number; fixture_limitation:string; prompt_version:string }
const { data, error } = useData<Config>('/settings')
</script>
<template>
  <div class="page-heading"><div><span class="eyebrow">WORKSPACE CONFIGURATION</span><h1>Settings & provider status</h1><p>Know how your catalog is processed.</p></div></div><Notice :error="error" />
  <div v-if="data" class="settings-grid"><section class="panel settings-card"><span class="icon-tile"><Sparkles :size="21" /></span><h2>AI provider</h2><span class="status" :class="data.provider_ready?'status-ready':'status-failed'">{{ data.provider_ready?'Ready':'Configuration required' }}</span><dl><div><dt>Processing mode</dt><dd>{{ data.mode==='fixture'?'Deterministic fixtures':'Real provider · OpenAI' }}</dd></div><div><dt>Chat model</dt><dd>{{ data.mode==='fixture'?'Synthetic record parser v1':data.chat_model }}</dd></div><div><dt>Embedding space</dt><dd class="mono">{{ data.embedding_space }}</dd></div><div><dt>Prompt version</dt><dd>{{ data.prompt_version }}</dd></div></dl><p class="info-strip">{{ data.mode==='fixture'?data.fixture_limitation:'Provider failures remain visible. The application never silently switches to fixture mode.' }}</p></section>
  <section class="panel settings-card"><span class="icon-tile"><SlidersHorizontal :size="21" /></span><h2>Processing limits</h2><dl><div><dt>Retrieval rounds</dt><dd>{{ data.max_retrieval_rounds }}</dd></div><div><dt>Active-job timeout</dt><dd>{{ data.max_run_seconds }} seconds</dd></div><div><dt>Worker concurrency</dt><dd>{{ data.worker_concurrency }}</dd></div><div><dt>Provider retries</dt><dd>{{ data.ai_limits.provider_retries }} per call</dd></div><div><dt>Input token estimate limit</dt><dd>{{ data.ai_limits.input_tokens.toLocaleString() }}</dd></div><div><dt>Output token limit</dt><dd>{{ data.ai_limits.output_tokens.toLocaleString() }}</dd></div><div><dt>Calls per batch or document</dt><dd>{{ data.ai_limits.scope_calls }}</dd></div><div><dt>Calls per workspace</dt><dd>{{ data.ai_limits.workspace_calls }}</dd></div><div><dt>Job attempts</dt><dd>3 maximum per automatic delivery</dd></div></dl><p>Review can remain paused indefinitely. Its state persists in PostgreSQL checkpoints.</p></section>
  <section class="panel settings-card"><span class="icon-tile"><Server :size="21" /></span><h2>Configure the local installation</h2><p>Set AI_MODE, OPENAI_API_KEY, CHAT_MODEL and EMBEDDING_MODEL in the server environment, then restart the API and worker. Provider keys are never returned to this browser.</p><p>After changing embedding configuration, run the documented reindex command before starting new enrichment runs.</p><a href="/api/docs" target="_blank" class="text-link">Open API documentation</a></section>
  <section class="panel settings-card"><span class="icon-tile"><ShieldCheck :size="21" /></span><h2>Data handling</h2><p>All retrieval, files, reviews and exports are restricted to your selected workspace. Reviewer permissions are checked again when changes are applied.</p><p>Text-based PDFs, TXT and CSV are supported. OCR, public-web crawling and automatic publication are outside this version.</p></section></div>
  <OperationsPanel />
</template>
